### ISSUE TITLE
README sample, results in: TypeError: The 'options' paramater must an object'

### ISSUE THREAD

**Issue by diit** [simonepri/sympact#1]
## I'm submitting a

- [x] bug report

## Checklist

- [x] Searched both open and closed issues for duplicates of this issue
- [x] Title adequately and *concisely* reflects the feature or the bug

## Information

Recreation [here](https://runkit.com/diit/js-code-profiling-test).

**Comment by simonepri** [comment]
@diit Thank you for the time spent opening this issue!

Closing it with: https://github.com/simonepri/sympact/commit/aa9550decd90d6ba7c346286cb2d5d6f52c671b6

Let me know if the problem still persists.
